/**
 * A curated list of 100 famous scientists, used as the default session name
 * when the user doesn't supply one. Picked uniformly at random.
 */
export const SCIENTIST_NAMES: readonly string[] = [
  'Albert Einstein',
  'Isaac Newton',
  'Marie Curie',
  'Charles Darwin',
  'Galileo Galilei',
  'Nikola Tesla',
  'Stephen Hawking',
  'Richard Feynman',
  'Niels Bohr',
  'Max Planck',
  'Erwin Schrödinger',
  'Werner Heisenberg',
  'Paul Dirac',
  'Enrico Fermi',
  'Wolfgang Pauli',
  'J. Robert Oppenheimer',
  'Rosalind Franklin',
  'James Watson',
  'Francis Crick',
  'Ada Lovelace',
  'Alan Turing',
  'Grace Hopper',
  'John von Neumann',
  'Claude Shannon',
  'Edsger Dijkstra',
  'Linus Torvalds',
  'Tim Berners-Lee',
  'Donald Knuth',
  'Dennis Ritchie',
  'Ken Thompson',
  'Alonzo Church',
  'Kurt Gödel',
  'Emmy Noether',
  'Carl Friedrich Gauss',
  'Leonhard Euler',
  'Pierre-Simon Laplace',
  'Henri Poincaré',
  'Srinivasa Ramanujan',
  'Alexander Grothendieck',
  'Bertrand Russell',
  'David Hilbert',
  'Andrey Kolmogorov',
  'Benoit Mandelbrot',
  'Georg Cantor',
  'Évariste Galois',
  'Bernhard Riemann',
  'Michael Faraday',
  'James Clerk Maxwell',
  'Lord Kelvin',
  'Ernest Rutherford',
  'J.J. Thomson',
  'Dmitri Mendeleev',
  'Linus Pauling',
  'Antoine Lavoisier',
  'Marie-Anne Lavoisier',
  'Robert Boyle',
  'Louis Pasteur',
  'Alexander Fleming',
  'Gregor Mendel',
  'Barbara McClintock',
  'Dorothy Hodgkin',
  'Rachel Carson',
  'Jane Goodall',
  'E.O. Wilson',
  'Alfred Wegener',
  'Carl Sagan',
  'Neil deGrasse Tyson',
  'Edwin Hubble',
  'Caroline Herschel',
  'William Herschel',
  'Jocelyn Bell Burnell',
  'Vera Rubin',
  'Subrahmanyan Chandrasekhar',
  'Lise Meitner',
  'Chien-Shiung Wu',
  'Maria Goeppert Mayer',
  'Hedy Lamarr',
  'Katherine Johnson',
  'Mae Jemison',
  'Sally Ride',
  'Karl Landsteiner',
  'Jonas Salk',
  'Francis Collins',
  'Craig Venter',
  'Paul Erdős',
  'John Nash',
  'Norbert Wiener',
  'Thomas Edison',
  'Alessandro Volta',
  'André-Marie Ampère',
  'Georg Ohm',
  'Heinrich Hertz',
  'Gottfried Wilhelm Leibniz',
  'Blaise Pascal',
  'Johannes Kepler',
  'Tycho Brahe',
  'Nicolaus Copernicus',
  'Aristotle',
  'Archimedes',
  'Euclid',
  'Hypatia',
  'Ibn al-Haytham',
];

export function pickScientistName(): string {
  return SCIENTIST_NAMES[Math.floor(Math.random() * SCIENTIST_NAMES.length)]!;
}
